name: Deploy

on:
  push:
    branches:
#      - master
      - feature/design

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "polar-oasis-91864"
          heroku_email: "vova.lunev@devhouse.pro"
          usedocker: true
          docker_heroku_process_type: "web"
          docker_build_args: |
            NODE_ENV
        env:
          NODE_ENV: production
